name: Publish to Sonatype

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Artifacts
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Generate POM file
        run: ./gradlew generatePomFileForMavenJavaPublication --no-daemon

      - name: Publish with Gradle
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingPublicKey: ${{ secrets.PGP_PUBLIC }}
        run: ./gradlew sonatypeCentralUpload --no-daemon